# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c608bf24675f1ec74625975bb0bdadf6aa3338f8d67178c23b4d9f1d946f436473807bd1238c4399ee5a9c97acd4e134bf58c43fc7e0a32451c2e612e43e0c95

test:
  secret_key_base: f61738aa487ccdb8fa89986965c4b10211a6b206a3ca447578bc83941664517114295b7714f5366335d99522479074208de85c1760837209daae291cbdede60b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
